config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :teams
  resources :matches
  resources :users

  root 'matches#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  has_and_belongs_to_many :teams

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    matches_sql = '
    SELECT m.id, m.location, m.home_score, m.away_score, m.date,    home_team.name AS home_team, away_team.name AS away_team
    FROM Matches as m
    INNER JOIN teams AS home_team ON home_team.id=m.home_team_id
    INNER JOIN teams AS away_team ON away_team.id=m.away_team_id'

    @matches = Match.find_by_sql(matches_sql)
    render json: {matches: @matches}
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @teams = Team.all
  end

  # GET /matches/new
  def new
    @match = Match.new
    @teams = Team.all
  end

  # GET /matches/1/edit
  def edit
    @teams = Team.all
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    @teams = Team.all

    respond_to do |format|
      if @match.update(match_params)
        flash.now[:notice] = 'Match was successfully updated'
        format.html { render :show, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:location, :date, :home_score, :away_score, :home_team_id, :away_team_id)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :match_location %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :match_date %>
  </div>

  <div class="field">
    <%= form.label :home_score %>
    <%= form.number_field :home_score, id: :match_home_score %>
  </div>

  <div class="field">
    <%= form.label :away_score %>
    <%= form.number_field :away_score, id: :match_away_score %>
  </div>

  <div class="field">
    <%= form.label :home_team_id %>
    <%= form.select :home_team_id, options_from_collection_for_select(@teams, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :away_team_id %>
    <%= form.select :away_team_id, options_from_collection_for_select(@teams, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Date</th>
      <th>Home score</th>
      <th>Away score</th>
      <th>Home</th>
      <th>Away</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.location %></td>
        <td><%= match.date %></td>
        <td><%= match.home_score %></td>
        <td><%= match.away_score %></td>
        <td><%= match.home_team_id %></td>
        <td><%= match.away_team_id %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @match.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @match.date %>
</p>

<p>
  <strong>Home score:</strong>
  <%= @match.home_score %>
</p>

<p>
  <strong>Away score:</strong>
  <%= @match.away_score %>
</p>

<p>
  <strong>Home:</strong>
  <%= @teams.find(@match.home_team_id).name %>
</p>

<p>
  <strong>Away:</strong>
  <%= @teams.find(@match.away_team_id).name %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>